/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab24;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ArayuzSorgu extends javax.swing.JFrame {
    private String kullaniciadi="root";
    private String parola="";
    private String host="127.0.0.1";
    private String db="prolab4";
    private int port=3306;
    private Connection conn=null;
    private ResultSet rs=null;
    private Statement pst=null;

    /**
     * Creates new form ARac4
     */
    public ArayuzSorgu() {
        String url="jdbc:mysql://"+this.host+":"+this.port+"/"+this.db;
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch(ClassNotFoundException e){
            System.out.println("mysql connector yok");
            e.printStackTrace();
        }
        try{
            this.conn= (Connection) DriverManager.getConnection(url,kullaniciadi,parola);
        }
        catch(SQLException e){
            System.out.println("Baglanti basarisiz");
            e.printStackTrace();
        }
        if(conn!=null){
            System.out.println("basardik");
        }
        else{
            System.out.println("basarisiz");
        }
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ComboSehir = new javax.swing.JComboBox<>();
        ComboTarih = new javax.swing.JComboBox<>();
        ComboYakit = new javax.swing.JComboBox<>();
        ComboRenk = new javax.swing.JComboBox<>();
        ComboVites = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttablo = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("SORGULAMA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("İLAN ADI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("FİYATI");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ŞEHİR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("İLAN TARİHİ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("MARKASI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("MODELİ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("KM");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("YAKIT TÜRÜ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("RENK");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("VİTES TÜRÜ");
        jLabel8.setToolTipText("");

        jButton1.setText("ARAMA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GERİ DÖN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel12.setText("MAX");

        jLabel13.setText("MİN");

        jLabel16.setText("MAX");

        jLabel17.setText("MİN");

        ComboSehir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seçiniz-", "Adana ", "Adıyaman ", "Afyonkarahisar ", "Ağrı ", "Amasya ", "Ankara ", "Antalya ", "Artvin ", "Aydın ", "Balıkesir ", "Bilecik ", "Bingöl ", "Bitlis ", "Bolu ", "Burdur ", "Bursa ", "Çanakkale ", "Çankırı ", "Çorum ", "Denizli ", "Diyarbakır ", "Edirne ", "Elazığ ", "Erzincan ", "Erzurum ", "Eskişehir ", "Gaziantep ", "Giresun ", "Gümüşhane ", "Hakkari ", "Hatay ", "Isparta ", "Mersin ", "İstanbul ", "İzmir ", "Kars ", "Kastamonu ", "Kayseri ", "Kırklareli ", "Kırşehir ", "Kocaeli ", "Konya ", "Kütahya ", "Malatya ", "Manisa ", "K.maraş ", "Mardin ", "Muğla ", "Muş ", "Nevşehir ", "Niğde ", "Ordu ", "Rize ", "Sakarya ", "Samsun ", "Siirt ", "Sinop ", "Sivas ", "Tekirdağ ", "Tokat ", "Trabzon ", "Tunceli ", "Şanlıurfa ", "Uşak ", "Van ", "Yozgat ", "Zonguldak ", "Aksaray ", "Bayburt ", "Karaman ", "Kırıkkale ", "Batman ", "Şırnak ", "Bartın ", "Ardahan ", "Iğdır ", "Yalova ", "Karabük ", "Kilis ", "Osmaniye ", "Düzce" }));
        ComboSehir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSehirActionPerformed(evt);
            }
        });

        ComboTarih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seçiniz-", "Son 24 Saat", "Son 1 Hafta", "Son 1 Ay" }));

        ComboYakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seçiniz-", "Benzin", "LPG", "Dizel", "Elektrik", "Hibrit" }));

        ComboRenk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seçiniz-", "Beyaz (Opak)", "Mistral Mavi (Opak)", "Alev Kırmızı (Metalik)", "Atlas Mavi (Metalik)", "Bakır Kahve (Metalik)", "Bulut Gri (Metalik)", "Platin Gri (Metalik)", "Yıldız Siyah (Metalik)" }));

        ComboVites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seçiniz-", "Manuel", "Otomatik", "Yarı Otomatik" }));

        txttablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(txttablo);

        jToggleButton1.setText("Sil");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(161, 161, 161))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12))
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11)
                            .addComponent(jTextField1)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(ComboSehir, 0, 1, Short.MAX_VALUE)
                            .addComponent(ComboTarih, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboYakit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboRenk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboVites, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ComboSehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ComboTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(ComboYakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboRenk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboVites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
        new ArayuzGiris().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked
    public ArrayList<User> UserList(){
         ArrayList<User> usersList = new ArrayList<>();
        String sorguCumle="*";
        
        String Ilan_Adi="%";
        String Ilan_Fiyat_Min="0";
        String Ilan_Fiyat_Max="99999999";
        String Ilan_Marka="%";
        String Ilan_Model="%";
        String Ilan_Km_Max="0";
        String Ilan_Km_Min="99999999";        
        Integer Ilan_Yakit=0;
        String Ilan_Yakit_String="%";
        Integer Ilan_Vites=0;
        String Ilan_Vites_String="%";
        Integer Ilan_Renk=0;
        String Ilan_Renk_String="%";
        Integer Ilan_Sehir=0;
        String Ilan_Sehir_String="%";
        
        
        
        
        if(!Ilan_Adi.equals("")){
            Ilan_Adi = jTextField1.getText();
        }
        
        if(!Ilan_Fiyat_Min.equals("")){
            Ilan_Fiyat_Min = jTextField2.getText();
        }
        
        if(!Ilan_Fiyat_Max.equals("")){
           Ilan_Fiyat_Max = Ilan_Fiyat_Max=jTextField11.getText();
        }
        
        if(!Ilan_Marka.equals("")){
            Ilan_Marka =jTextField5.getText();
        }
        
        if(!Ilan_Model.equals("")){
            Ilan_Model =jTextField6.getText();
        }
        
        if(!Ilan_Km_Max.equals("")){
            Ilan_Km_Max = jTextField7.getText();
        }
        
         if(!Ilan_Km_Min.equals("")){
            Ilan_Km_Min = jTextField12.getText();
        }
        
        if(ComboYakit.getSelectedIndex()!=0){
            Ilan_Yakit=ComboYakit.getSelectedIndex();
        }
        
        if(ComboVites.getSelectedIndex()!=0){
            Ilan_Vites=ComboVites.getSelectedIndex();
        }
        
        if(ComboRenk.getSelectedIndex()!=0){
          Ilan_Renk =  ComboRenk.getSelectedIndex();
        }
        Ilan_Sehir_String = "%";
        if(ComboSehir.getSelectedIndex()!=0){
            Ilan_Sehir = ComboSehir.getSelectedIndex();
             Ilan_Sehir_String= Ilan_Sehir.toString();
        }
        
        int Ilan_Tarih=ComboTarih.getSelectedIndex();
        

        Statement ac=null;
        try {
            ac = (Statement) conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(ArayuzSorgu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        //Sorgu
        
        
        try {
            String sq123 = "SELECT * FROM tbl_araba,tbl_ilan,tbl_sehir,tbl_yakitturu,tbl_vitesturu,tbl_renk WHERE "
                    + "tbl_ilan.Ilan_ArabaID=tbl_araba.ArabaID "
                    +"                     AND (tbl_araba.Araba_RenkID = tbl_renk.Renk_ID) "
                    +"					 AND (tbl_araba.Araba_VitesTuruID = tbl_vitesturu.VitesTuruID) "
                    +"                     AND (tbl_araba.Araba_YakitTuruID = tbl_yakitturu.YakitTuruID) "
                    +"                     AND (tbl_ilan.Ilan_SehirID = tbl_sehir.Sehir_ID) "
                    +"AND (SELECT Sehir FROM tbl_sehir WHERE Sehir_ID = tbl_ilan.Ilan_SehirID ) like (SELECT Sehir FROM tbl_Sehir WHERE Sehir_ID='" + Ilan_Sehir_String + "') "
                    + "AND  (tbl_ilan.Ilan_Adi like '" + Ilan_Adi + "')"
                    + "AND  (tbl_ilan.Ilan_Fiyat between '" + Ilan_Fiyat_Min + "' AND '" + Ilan_Fiyat_Max + "')"
                    + "AND  (tbl_ilan.Ilan_Km between '" + Ilan_Km_Min + "' AND '" + Ilan_Km_Max + "')"
                    + "AND tbl_araba.Araba_Marka in (SELECT Araba_Marka FROM tbl_araba WHERE Araba_Marka like '" + Ilan_Marka + "')"
                    + "AND tbl_araba.Araba_Model in (SELECT Araba_Model FROM tbl_araba WHERE Araba_Model like '" + Ilan_Model + "')" 
                    + "AND ( (SELECT Renk FROM tbl_renk WHERE Renk_ID = tbl_araba.Araba_RenkID) like (SELECT Renk FROM tbl_renk WHERE Renk_ID= '"+Ilan_Renk_String+"')) "
                    + "AND ( (SELECT Vites_Turu FROM tbl_vitesturu WHERE VitesTuruID = tbl_araba.Araba_VitesTuruID) like (SELECT Vites_Turu FROM tbl_vitesturu WHERE VitesTuruID= '"+Ilan_Vites_String+"'))"
                    + "AND ( (SELECT Yakit_Turu FROM tbl_yakitturu WHERE YakitTuruID = tbl_araba.Araba_YakitTuruID) like (SELECT Yakit_Turu FROM tbl_yakitturu WHERE YakitTuruID= '"+Ilan_Yakit_String+"'))  ";
            
            
            
            String sorgu_Sehir=null;
            String sorgu_Ad=null;
            String sorgu_Fiyat=null;
            String sorgu_Marka=null;
            String sorgu_Model=null;
            String sorgu_Km = null;
            String sorgu_YakitTuru = null;
            String sorgu_VitesTuru = null;
            String sorgu_Renk = null;
            ResultSet sonuclar= ac.executeQuery(sq123);
            
             User user;
            while(sonuclar.next()){
                user=new User (sonuclar.getString("Sehir"),sonuclar.getString("Ilan_Adi"),sonuclar.getString("Ilan_Fiyat"),sonuclar.getString("Araba_Marka"),sonuclar.getString("Araba_Model"),sonuclar.getString("Ilan_Km"),sonuclar.getString("Yakit_Turu"),sonuclar.getString("Vites_Turu"),sonuclar.getString("Renk"));
                usersList.add(user);
            }
            //conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(ArayuzSorgu.class.getName()).log(Level.SEVERE, null, ex);
        }
        return usersList;
    }
    private  DefaultTableModel model;
   
    public void show_user(){
        ArrayList<User> list = UserList();
        DefaultTableModel model =(DefaultTableModel) txttablo.getModel();
        Object[] row = new Object [11];
        for(int i = 0 ;i<list.size();i++){
            row[0]=list.get(i).getIlanAdi();
            row[1]=list.get(i).getIlanFiyat();
            row[2]=list.get(i).getMarka();
            row[3]=list.get(i).getModel();
            row[4]=list.get(i).getRenk();
            row[5]=list.get(i).getVitesTuru();
            row[6]=list.get(i).getYakitTuru();
            row[7]=list.get(i).getIlanKM();
            row[8]=list.get(i).getIlanSehir();
            model.addRow(row);
        }
        
    }
    
   
  void reset() {
    ArrayList<User> list = UserList();
        model = (DefaultTableModel) txttablo.getModel();
        Object[] row = new Object [11];
        for(int i = 0 ;i<list.size();i++){
            row[0]=list.get(i).getIlanAdi();
            row[1]=list.get(i).getIlanFiyat();
            row[2]=list.get(i).getMarka();
            row[3]=list.get(i).getModel();
            row[4]=list.get(i).getRenk();
            row[5]=list.get(i).getVitesTuru();
            row[6]=list.get(i).getYakitTuru();
            row[7]=list.get(i).getIlanKM();
            row[8]=list.get(i).getIlanSehir();
            model.addRow(row);
        }
        
      model.setRowCount(0);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserList();
        show_user();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboSehirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSehirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSehirActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        reset();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArayuzSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArayuzSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArayuzSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArayuzSorgu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArayuzSorgu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboRenk;
    private javax.swing.JComboBox<String> ComboSehir;
    private javax.swing.JComboBox<String> ComboTarih;
    private javax.swing.JComboBox<String> ComboVites;
    private javax.swing.JComboBox<String> ComboYakit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable txttablo;
    // End of variables declaration//GEN-END:variables
}
